### ISSUE TITLE
Weird vuejs interaction

### ISSUE THREAD

**Issue by Herz3h** [nadchif/html-duration-picker.js#100]
**Describe the bug**
Trying to use this with vuejs makes it kinda hard to use. 

Basically any time you type a number while being on the hours part, it immediately shifts to minutes (Typing 1 while being on hours, shifts to minutes). 

Thus making it impossible to type hours completely.

**To Reproduce**
`git clone https://github.com/Herz3h/test-html-duration-picker`
`yarn install`
`yarn serve`
Go to `http://localhost:8080/`
Put cursor on hours and type any number

**Expected behavior**
It should stay on hours until it is done then it should shift to minutes.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Catalina
 - Browser [e.g. chrome, safari] Chrome 85.0.4183.121 (64bits)
 - Version [e.g. 22] 2.2.8 (latest)

**Additional context**

**Edit**: After trying to figure out the problem, it seems that it really depends where you click. If say I have this duration:

`12:34`

And click on the 2, the above weird behavior happens. However clicking on the 1, it behaves as expected. 

Wouldn't it be better if we put cursor to leftmost digit on every click (If I click hours it goes to leftmost digit, if I click minutes it goes to leftmost digit) ?

**Comment by nadchif** [comment]
Thank you @Herz3h for raising this issue. I will look into it as soon as possible.

I love the suggestion of moving the cursor to the left most digit, I think that will be the solution we will implement

**Comment by Herz3h** [comment]
At the end, I think it was a problem with how I used to plugin with vuejs. Instead of `:value` and `@input`, I now use `v-model` with duration being already formatted (instead of number of minutes only, I now specify duration as hh:mm).

The problem is gone this way. So I think its a usage problem with vuejs rather than really being related to the plugin. 

Therefore I'll just close the issue, rather than wasting your time 👍

**Comment by nadchif** [comment]
Thank you once again @Herz3h. May I invite you to share how you implemented it in our documentation https://github.com/nadchif/html-duration-picker.js/blob/master/DOCUMENTATION.md#Angular. It may help someone 🙏
