### ISSUE TITLE
Ability to limit number of digits for hours

### ISSUE THREAD

**Issue by Herz3h** [nadchif/html-duration-picker.js#101]
**Is your feature request related to a problem? Please describe.**
Currently you can have as many digits in hours as you want. And this is annoying since, sometimes:

- You don't want users to type in more than N digits for hours
- Allowing unlimited number of digits for hours, doesn't autoswitch to minute after being done typing hours

**Describe the solution you'd like**
Attribute or js option to specify number of maximum digits for hours (by default set to infinite for BC)

**Describe alternatives you've considered**
An alternative would be, binding TAB key so you can easily switch between hours and minutes, and so on (I know arrow key do that, but they are too far away from left side of keyboard, and imo not very intuitive)

**Additional context**
-

**Comment by nadchif** [comment]
**UPDATE:** Thanks to @AlyxMoon , <kbd>Tab</kbd> key support has been added.

**TODO:** Implement

> Attribute or js option to specify number of maximum digits for hours (by default set to infinite for BC)

**Comment by AlyxMoon** [comment]
I will grab this up.

**Comment by tanishkachitnis22** [comment]
Is this still open for grabs I would love to grab

**Comment by nadchif** [comment]
@tanishkachitnis22 thank you, please take a look at https://github.com/nadchif/html-duration-picker.js/pull/104 first

**Comment by nadchif** [comment]
This feature is now partially implemented in version [2.3.4](https://www.npmjs.com/package/html-duration-picker/v/2.3.4). The behavior now is the picker will figure out the maximum hour digits based on the max-duration-value provided. By default the max-duration-value will be set to 99:59:59, hence setting the maximum hour digits to 2
