### ISSUE TITLE
Default class name for the target element is being replaced

### ISSUE THREAD

**Issue by dstokovsky** [nadchif/html-duration-picker.js#113]
https://github.com/nadchif/html-duration-picker.js/blob/2b216b8afcd1f45ebe54dc4c1ece31327c221d76/src/html-duration-picker.js#L385

It seems to be a problem, at least for me. I need an element I assigned duration picker to have also other classes. Unfortunately, the aforementioned line replaces everything with pickerStyles value.

**Comment by nadchif** [comment]
Nice catch! Thank you for this observation
