### ISSUE TITLE
Feature: Add support for negative values

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#132]
**Current Behavior**
Right now the duration timer accepts any value equal to or higher than `00:00:00`

**Wanted Behavior**
Add support for negative values like `-00:03:00`

### Discussed in https://github.com/nadchif/html-duration-picker.js/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **dev-hardev** September 28, 2021</sup>
Hello everyone,
I want to insert a negative time value in DB.
How can I get a negative duration value in HTML form?</div>

**Comment by adaniello** [comment]
Only a thought: "duration" is "NOT negative" by definition.

So, if a need also a negative value, i'ld add another input to manage sign.

**Comment by nadchif** [comment]
@adaniello  thank you for that input, that makes sense. Using a secondary in put is a simple yet brilliant solution. 

With that I think we can close this issue for now
