### ISSUE TITLE
Arrow left and Arrow Right key to move focus between hh, mm, and ss

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#14]
**Current Behavior:**
The Arrow Left <kbd><-</kbd> and Arrow Right <kbd>-></kbd> keys are disabled from working within the duration picker.

**Wanted Behavior:**
When a user is in the `hh` region like this:
 
![Screen Shot 2019-12-03 at 11 34 42 AM](https://user-images.githubusercontent.com/47924887/70038525-0da4d880-15c1-11ea-906e-d132623e09a5.png)
and a user presses the arrow right <kbd>-></kbd> the focus it should jump to `mm`, like this:

![Screen Shot 2019-12-03 at 11 34 54 AM](https://user-images.githubusercontent.com/47924887/70038617-3a58f000-15c1-11ea-85eb-934cb8fc209d.png)

**Comment by jkreller** [comment]
Hey! I would like to try this one. I am actually a first-timer and that would be my first pull request in a public repository on GitHub, but I feel like I want something challenging and that seems to fit better for me then #22. :)

**Comment by nadchif** [comment]
@jkreller welcome to the Open Source universe. Love that spirit you have. Please keep it up 💯 

Jump right in, and please feel welcome to ask for any assistance if you need it.

**Comment by jkreller** [comment]
According to your reusable code it was actually faster then I expected :) See #27

**Comment by nadchif** [comment]
Thank you @jkreller for the awesome work bringing us this enhancement. If you sport any issues or think of other enhancement features, please feel welcome to raise an issue.

**Comment by nadchif** [comment]
Thank you @jkreller for the awesome work bringing us this enhancement. If you sport any issues or think of other enhancement features, please feel welcome to raise an issue.

**Comment by jkreller** [comment]
Thanks for you warm welcome 🙏 I would love to collaborate more within this project.

**Comment by nadchif** [comment]
Most welcome. Please feel welcome to tackle any other issues or add features.
