### ISSUE TITLE
Duration picker is not changing the model value when using up or down arrow.

### ISSUE THREAD

**Issue by JojoOrion** [nadchif/html-duration-picker.js#140]
**Describe the bug**
Duration picker is not changing the model value when using up or down arrow. It works fine when I directly enter the value using keyboard.

**To Reproduce**

Use Duration picker using new Angular project, take developer tool, pick the element.

**Expected behavior**
Same behavior should happen for both keyboard input and up and down arrow click

**Screenshots**
![image](https://user-images.githubusercontent.com/99623724/153783390-4c1fcaed-00de-4481-81fc-9cbc349735c4.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Any

**Comment by nadchif** [comment]
Thank you @JojoOrion for raising this issue

**Comment by longtongj28** [comment]
Hello, I know that I have already done the other issue, but do you mind if I pick this one up as well? Thanks.

**Comment by nadchif** [comment]
Sure, please go ahead @longtongj28 🚀

**Comment by nadchif** [comment]
> Can I help for this ?

Hi @Liaxum thank you for your willingness to help 😄 Let's wait for a confirmation from @longtongj28

**Comment by Liaxum** [comment]
Sure :smiley:

**Comment by longtongj28** [comment]
@Liaxum I would love and appreciate the help, but I'm actually contributing for a university assignment so I'm not sure if I would be allowed to do that

**Comment by Liaxum** [comment]
@longtongj28 maybe you should ask to your university if it's possible do be helped another one. (Same for me it's for my studies 😉)

**Comment by longtongj28** [comment]
Ok I just asked, he said its ok, you can do it too

**Comment by nadchif** [comment]
Thank you @longtongj28 and @Liaxum for collaborating on this. I'm okay with this arrangement 👍

**Comment by nadchif** [comment]
Hi @longtongj28 and @Liaxum, will un-assign you on this issue as I haven't since heard from either one of you, however please feel welcome to let me know If you would still be interested in taking this issue

**Comment by lukeshafer** [comment]
Hi @nadchif! I'd like to try tackling this one - it would be my first open source contribution

**Comment by lukeshafer** [comment]
So I made a commit fixing this issue - but unfortunately I couldn't get testing to work 😦 -- even on a fresh clone without my changes, the testing would throw an error. 

Anyways, I'll submit the pull request for review. @nadchif please let me know if there is anything else you need!

**Comment by lukeshafer** [comment]
> So I made a commit fixing this issue - but unfortunately I couldn't get testing to work 😦 -- even on a fresh clone without my changes, the testing would throw an error.
> 
> Anyways, I'll submit the pull request for review. @nadchif please let me know if there is anything else you need!

To be clear - the Jasmine testing is what failed. Everything passed under ESLint

**Comment by sheldebaume** [comment]
Hi
I've tested the fix on my side.
Model value is correctly updated.
But there is a problem when increasing/decreasing the hour using the arrows : it switches automatically to the minutes after clicking on it.
I guess it's what cause the jasmine test failed.
![bug_duration](https://user-images.githubusercontent.com/91215096/205107529-3a948843-1bcb-4550-b413-34882c0d2a6b.gif)
Any idea to solve this ?
Thanks,
Steve

**Comment by wyntonfranklin** [comment]
Hi @sheldebaume,

You can call this function after the scrollUpBtn and scrollDownBtn presses.

`highlightTimeUnitArea(inputBox, adjustmentFactor);` 

just get the adjustmentFactor before `changeValueByArrowKeys` is called.
I'm also not sure the `setInterval` function on `changeValueByArrowKeys` is helping.

@nadchif can I be allowed to commit my changes it would be a first for me.

**Comment by nadchif** [comment]
Hi @wyntonfranklin, thank you for the work you did towards solving this issue. 

May you open a separate pull request from your Fork?

**Comment by nadchif** [comment]
Sure @wyntonfranklin thank you for opening https://github.com/nadchif/html-duration-picker.js/pull/164

**Comment by sheldebaume** [comment]
Hi @nadchif 
any time to merge #164 to master and make a new release if it solves the issue ?
Thanks !

**Comment by nadchif** [comment]
> Hi @nadchif any time to merge #164 to master and make a new release if it solves the issue ? Thanks !

Sorry for the delay @sheldebaume. Just released 🎉

**Comment by sheldebaume** [comment]
> > Hi @nadchif any time to merge #164 to master and make a new release if it solves the issue ? Thanks !
> 
> Sorry for the delay @sheldebaume. Just released 🎉

You rock, thanks a lot @nadchif

**Comment by sheldebaume** [comment]
@nadchif @wyntonfranklin  just tested it today, works like a charm, thanks.
