### ISSUE TITLE
Wrong data-hide-seconds behavior

### ISSUE THREAD

**Issue by rettiseert** [nadchif/html-duration-picker.js#143]
When using the data-hide-seconds option, the seconds are hidden upon initialization, but once the input gets and loses focus they appear again. This behavior can be seen on the [demo page](https://nadchif.github.io/html-duration-picker.js)

![Animation](https://user-images.githubusercontent.com/25987733/157339536-addceee0-5376-43af-9eaf-45a245ba9a22.gif)

Think there's a chance to fix this?

Thanks!

**Comment by nadchif** [comment]
Thank you @rettiseert for raising this. Yes, it can be fixed 😊

**Comment by longtongj28** [comment]
Hi can you assign this to me?

**Comment by danlsw** [comment]
Sure @longtongj28

**Comment by nadchif** [comment]
Sure @longtongj28 . Thank you
