### ISSUE TITLE
Update landing page to use latest version of picker

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#147]
**Good for first timers**

CURRENT ISSUE: The file [src/index.html](https://github.com/nadchif/html-duration-picker.js/blob/master/src/index.html) uses a fixed version (2.3.4). Right now the code is like this:
```html
77.    <script src="https://cdn.jsdelivr.net/npm/html-duration-picker@2.3.4/dist/html-duration-picker.min.js"></script>
```

WHAT WE NEED: Instead of using a set version, we need to just use the latest npm version available. It should end up something like this:
```
77.    <script src="https://cdn.jsdelivr.net/npm/html-duration-picker@latest/dist/html-duration-picker.min.js"></script>
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by cmcgee0308** [comment]
Hi there! Can I be assigned to this issue?

**Comment by nadchif** [comment]
> Hi there! Can I be assigned to this issue?

Yes please ☺

**Comment by cmcgee0308** [comment]
Hi! My pull request is ready to be reviewed! :)

**Comment by nadchif** [comment]
Fixed in https://github.com/nadchif/html-duration-picker.js/commit/c582ff51473da2bf68ac1f26891234149056a7ec
