### ISSUE TITLE
Punctuate and correct spellings in comments

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#15]
Good for first timers

CURRENT ISSUE: Not all the comments within [html-duration-picker.js](https://github.com/nadchif/html-duration-picker.js/blob/master/src/html-duration-picker.js) are properly punctuated. For example, if you go to line 93, you find
```
// increase time value;

```
WHAT WE NEED: The punctuation and capitalization should be fixed. For example, line 93 would become:
```
// Increase time value
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by ikayz** [comment]
@nadchif I'll work on this issue

**Comment by nadchif** [comment]
@ikayz Thank you. Go for it :-)

**Comment by GeorgeChambi** [comment]
Can I help with this?

**Comment by nadchif** [comment]
@GeorgeChambi thank you for your interest in helping us with this issue. @ikayz is currently assigned on this task, let's give him some time to work on it first.
In the meantime, would you like me to update you if more good first issues come up?

**Comment by GeorgeChambi** [comment]
Sure, thanks.

**Comment by nadchif** [comment]
@GeorgeChambi would you be interested in https://github.com/nadchif/html-duration-picker.js/issues/21 ?

**Comment by nadchif** [comment]
This issue has already been addressed in the code refactor: https://github.com/nadchif/html-duration-picker.js/pull/34
