### ISSUE TITLE
Fix spellings and punctuation in DOCUMENTATION.md

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#2]
Great for first timers.

Correct the spellings and punctuation in DOCUMENTATION.md. Sentences should start with capital letters etc. 

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by ikayz** [comment]
Can I work on this?

**Comment by nadchif** [comment]
@ikayz sure, yes please :-)

**Comment by AregbesolaOJ** [comment]
Can i jump on this please?

**Comment by nadchif** [comment]
@AregbesolaOJ thank you for your interest in helping us with this issue. @ikayz is currently assigned on this task, let's give him some time to work on it first.
In the meantime, would you like me to update you if more good first issues come up?

**Comment by AregbesolaOJ** [comment]
Thanks for getting back in touch. Oh yes please do, would appreciate that

**Comment by nadchif** [comment]
@AregbesolaOJ woukd you be interested in working on this issue
https://github.com/nadchif/html-duration-picker.js/issues/9?

**Comment by nadchif** [comment]
@AregbesolaOJ would you be interested in working on this issue https://github.com/nadchif/html-duration-picker.js/issues/22 ?
