### ISSUE TITLE
Add cursor style [Task 2] in html-duration-picker.js

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#22]
Great for first timers.

1. Add `cursor:default;` to Line 249 after `border:none;` in [html-duration-picker.js](https://github.com/nadchif/html-duration-picker.js/blob/master/src/html-duration-picker.js)

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by fsuffieldcode** [comment]
Can I pick this up?

**Comment by nadchif** [comment]
@fsuffieldcode yes please :)

**Comment by fsuffieldcode** [comment]
@nadchif Thanks for my first issue. I don't see this on line 226 though, is it perhaps line 249?

**Comment by nadchif** [comment]
@fsuffieldcode thank you for pointing that out. You are correct. The code has changed. We need that on line 249.

**Comment by fsuffieldcode** [comment]
Thanks. I'm trying to sync my fork and when I use 'git fetch upstream' I get:

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by fsuffieldcode** [comment]
@nadchif One extra thing I had to do that wasn't mentioned on CONTRIBUTING.md was:

`git remote add upstream https://github.com/nadchif/html-duration-picker.js`

So I've made the changes to the code but I don't know how to open the pull request? I've committed and pushes the changes but the pull request doesn't come up on https://github.com/nadchif/html-duration-picker.js/compare?expand=1.

Could you please help me out?

**Comment by nadchif** [comment]
@fsuffieldcode thank you for pushing through so far. Please see this guide on how to open the pull request https://opensource.com/article/19/7/create-pull-request-github.
If you still need anymore assistance please feel welcome ask again

**Comment by fsuffieldcode** [comment]
@nadchif I appreciate the help. I saw that article you linked, but it mentioned creating a branch. I thought I wouldn't need to branch?

**Comment by nadchif** [comment]
I see, okay for your convenience, try to use this link then https://github.com/fsuffieldcode/html-duration-picker.js/pull/new/master

**Comment by fsuffieldcode** [comment]
Thanks, but I don't understand why I couldn't see the pull request option on Github.

**Comment by nadchif** [comment]
Thank you @fsuffieldcode for your assistance with this issue. If you spot any other issue or think of features to improve the project, please feel welcome to raise an issue.

**Comment by nadchif** [comment]
> Thanks, but I don't understand why I couldn't see the pull request option on Github.

Thank you...don't worry you will soon master your way around Github, for now let's celebrate your awesome contribution 🥇 

I also found this guide helpful, https://gist.github.com/Chaser324/ce0505fbed06b947d962
