### ISSUE TITLE
Add a data-default-value attribute functionality to picker

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#28]
This issue may not be ideal for first timers. If you want first timer friendly issues, kindly go [here](https://github.com/nadchif/html-duration-picker.js/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [here](https://github.com/nadchif/html-duration-picker.js/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only)

**Current Behavior**
Right now the duration timer starts with `00:00:00` and whenever there is invalid input, it falls back to `00:00:00`

**Wanted Behavior**
It would be nice if we can implement a `data-default-value` attribute or something similar. So if a user did this 
```
<input html-duration-picker data-default-value="00:30:00">
```
Then the default value would be `00:30:00`

**Additional context**
If you have suggestions or think of a better `data-*` attribute name for this feature, we are open to discussion.

**Comment by PeterMorganGH** [comment]
I think `data-default-duration` would be a more descriptive name for the attribute. While technically you are setting a "value", the value = duration.

**Comment by nadchif** [comment]
You are right, that actually sounds better. I love it 💯

**Comment by nadchif** [comment]
Many thanks @PeterMorganGH for helping us out once again with this issue 🥇 . I'm sure you know by now, if you notice any bugs or think of features to add, please feel welcome to open an issue.
