### ISSUE TITLE
Suggestion for increaseValue and decreaseValue Functions Refactor

### ISSUE THREAD

**Issue by PeterMorganGH** [nadchif/html-duration-picker.js#33]
Starting on line 96 of https://github.com/nadchif/html-duration-picker.js/blob/2000d6a6ec76172d692f1cae473c9a34157ab76a/src/html-duration-picker.js#L96 the 2 functions are similar enough that you could refactor them - if you wanted to.

The main difference...

increaseValue():
```javascript
secondsValue += adjustmentFactor;
```
decreaseValue():
```javascript
secondsValue -= adjustmentFactor;
  if (secondsValue < 0) {
    secondsValue = 0;
  }
```

My suggestion would be to combine the functions and add a parameter to differentiate the 2 actions.
```javascript
const changeValue = (inputBox, direction) => {
  const rawValue = inputBox.value;
  const sectioned = rawValue.split(':');
  const adjustmentFactor = getAdjustmentFactor(inputBox);
  let secondsValue = 0;
  if (sectioned.length === 3) {
    secondsValue = Number(sectioned[2]) + Number(sectioned[1] * 60) + Number(sectioned[0] * 60 * 60);
  }
  switch (direction){
    case "up":
      secondsValue += adjustmentFactor;
      break;
    case: "down":
      secondsValue -= adjustmentFactor;
      if (secondsValue < 0) {
        secondsValue = 0;
      }
      break;
  }  
  insertFormatted(inputBox, secondsValue);
  highlightIncrementArea(inputBox, adjustmentFactor);
};
```

This could save 14 lines of code, but more importantly would make it so that you don't need to make the same changes twice. If you do decide to make this change, be sure to update the function calls on lines 176, 179, 262, 263, 265, and 266 with the additional parameter.

**Comment by nadchif** [comment]
@PeterMorganGH Thank you for this valuable analysis. This would definitely reduce the size of the library. Would you be willing to assist us with refactoring the code as suggested?

**Comment by PeterMorganGH** [comment]
@nadchif I will make the changes and submit a Pull Request.

**Comment by nadchif** [comment]
@PeterMorganGH thank you so much 🙏 We really appreciate this

**Comment by nadchif** [comment]
@PeterMorganGH thank you so much for the help with this issue. Thank you for going above and beyond. The code looks so nice now, its even pleasant to read :) Thanks again.

If you spot other issues or think of other enhancements to add to this project, please feel welcome to raise an issue
