### ISSUE TITLE
Change "html-duration-picker" attribute into valid HTML

### ISSUE THREAD

**Issue by jkreller** [nadchif/html-duration-picker.js#38]
**Is your feature request related to a problem? Please describe.**
The current way to implement the html-duration-picker is by adding "html-duration-picker" to the input like this: `<input html-duration-picker>`.
That's simple, but in my understanding this is not valid HTML.

**Describe the solution you'd like**
In my opinion the best solution would be to turn this custom attribute into a class, so that it can be implemented like that: `<input class="html-duration-picker">`.

**Comment by nadchif** [comment]
@jkreller this is true. Thank you @jkreller. Would you please lead us in the task of refactoring the code?

**Comment by jkreller** [comment]
Oh, I would have done this too, but you was actually faster 😅

**Comment by nadchif** [comment]
🤣 🤣 We try to work fast. Thank you for raising this issue. If you spot any other issues or think of an enhancement feature, please feel welcome to open an issue
