### ISSUE TITLE
Change 'demp' to 'demo' in README.md

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#4]
Great for first timers.

Correct the spellings  'Demp' to 'Demo' in README.md

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by ChamuMutezva** [comment]
Thanks @nadchif , i will take this one.

**Comment by nadchif** [comment]
@ChamuMutezva Sure, thank you :-)
