### ISSUE TITLE
Add 'download' link on Github Page

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#5]
Great for first timers.

Update index.html (located in the root) to have a download link to **html-duration-picker.min.js** located in the **dist** folder. The link should point to: https://github.com/nadchif/html-duration-picker.js/raw/master/dist/html-duration-picker.min.js

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by KKghub** [comment]
I have never created any pull request in github. I would like to work on this issue.

**Comment by nadchif** [comment]
@KKghub sure, please do. Thank you

**Comment by KKghub** [comment]
I believe `index.html` file present in the project is being served on your [github page](https://nadchif.github.io/html-duration-picker.js/)
There is already a link present to `html-duration-picker.min.js` under Example Usage section, but clicking on it opens the minified js file in the browser itself.
Do you want that link to be downloading the minified js or you want a seperate header and section on that page to download it.

**Comment by nadchif** [comment]
@KKghub you are right, there is a link already.  Just above the Example Usage, could you please create a prominent "Download" button or link, that will also link to the same ```html-duration-picker.min.js```

**Comment by KKghub** [comment]
Any suggestions on how to preview the html as I can't preview in my local machine?

**Comment by nadchif** [comment]
The simplest way would be to:
1. Fork the project
![Screen Shot 2019-12-01 at 5 13 45 PM](https://user-images.githubusercontent.com/47924887/69916004-1af58200-145e-11ea-9c7e-47b884921848.png)

2. Head to your copy of the fork and you should see ```index.html``` See Image below: It is right at the bottom.
![Screen Shot 2019-12-01 at 5 14 15 PM](https://user-images.githubusercontent.com/47924887/69916011-2cd72500-145e-11ea-9b0b-02f425adb8fb.png)

**Comment by nadchif** [comment]
@KKghub Thank you for bringing that to my attention.

 I now see how this may not be a very easy task for a first timer.  However, if you are still interested, here is a guide on how to do it: https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

**Comment by KKghub** [comment]
I tried following the article but I am facing issues. I don't feel confident enough to complete this task. Kindly unassign me from this issue.

Thank you

**Comment by nadchif** [comment]
Okay, Thank you  @KKghub

**Comment by ikayz** [comment]
@nadchif Can I work on this issue if no one is?

**Comment by nadchif** [comment]
@ikayz sure, would appreciate that :-)

**Comment by ikayz** [comment]
@nadchif I added the download link, albeit it does not download the html-duration-picker file instead it opens in the browser.

**Comment by nadchif** [comment]
@ikayz  thank you once again for the nice work. Please go ahead and open a pull request.

**Comment by ikayz** [comment]
@nadchif okay, I'll commit and do that.

**Comment by nadchif** [comment]
@ikayz Thank you once again for your help on this issue 👍
