### ISSUE TITLE
Adjust arrow holding and mouse holding to same speed

### ISSUE THREAD

**Issue by jkreller** [nadchif/html-duration-picker.js#50]
**Is your feature request related to a problem? Please describe.**
When one increase or decrease by holding down arrow keys it currently scrolls faster than holding down with my mouse on the arrow icons.

**Describe the solution you'd like**
I would like that the value increases in the same speed, no matter if I press and hold a _key_ **or** the _arrow icon with my mouse_.

**Comment by nadchif** [comment]
@jkreller Thank you for raising this issue.  That's an interesting observation. Are you in a position to work on a solution for this?

**Comment by jkreller** [comment]
@nadchif Today not but probably the next day(s). I also think that this issue might be a good first issue (probably with some help provided).

**Comment by ShivamArya2357** [comment]
I would like to work on this issue

**Comment by ShivamArya2357** [comment]
I have created pull request, please review: https://github.com/nadchif/html-duration-picker.js/pull/58/commits/913ef1b6cc9b3c24567dcb028307feb8169e808d
