### ISSUE TITLE
Improve UX on mobile devices

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#61]
This issue may not be ideal for first timers. If you want first timer friendly issues, kindly go [here](https://github.com/nadchif/html-duration-picker.js/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [here](https://github.com/nadchif/html-duration-picker.js/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only)

**Current Behavior**
The picker works very well on desktop/tablet. On a mobile device, the buttons are too small, and practically unusable.

**Wanted Behavior**
It would be nice if we can offer better UX on mobile devices or small screen. Some methods could be:
* On mobile, the picker defaults to a larger size. 

* On mobile, when a user taps the picker, it pop ups a larger, picker. Similar to this: 
![picker1](https://user-images.githubusercontent.com/47924887/79066308-364b8600-7cb7-11ea-812c-8a8eac04d716.png)
![Screen Shot 2020-04-12 at 12 16 30 PM](https://user-images.githubusercontent.com/47924887/79066370-af4add80-7cb7-11ea-94c5-8d63594f3157.png)

**Additional context**
If you have suggestions or think of a better idea for this feature, we are open to discussion.

**Comment by Iceberg1109** [comment]
Hi, @nadchif 

I'd like to help you with this issue.
Is this issue still open?

Thanks

**Comment by devTeaa** [comment]
Hi @nadchif is this issue still open for assignee?

**Comment by nadchif** [comment]
Yes, would you like to take it?

**Comment by devTeaa** [comment]
are css files allowed @nadchif ?

**Comment by nadchif** [comment]
Wow @devTeaa this looks awesome!!! 
I think tapping anywhere outside (as you have already implemented)  would be a great way to dismiss the mobile ui

**Comment by devTeaa** [comment]
@nadchif #99
