### ISSUE TITLE
Picker receives focus when user hovers over buttons

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#89]
**Describe the bug**
When you hover over the button carets, and you move your mouse away, the picker receives focus

**To Reproduce**
1. Load a page with a duration picker input box
2. Move your mouse to hover either a up <kbd>^</kbd> or <kbd>v</kbd>  button. 
3. Without clicking anything, move your mouse away.

**Expected behavior**
If a user hovers past a button, the picker should automatically get focus

**Screenshots**
![bugdemo](https://user-images.githubusercontent.com/47924887/82307678-f87e0380-99c0-11ea-9da6-a9d6dde383a1.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser: Chrome
 - Version: 81

**Comment by Kharanshu31** [comment]
Hi,I want to work on this and please guide me through

**Comment by nadchif** [comment]
Sure, thank you ☺
Please to through this for a step by step guide https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md

Feel welcome to reach out again if you still need assistance

**Comment by Kharanshu31** [comment]
i am not able to run the code in my machine

**Comment by Kharanshu31** [comment]
so basically i have to remove the focus when we move the mouse away?

**Comment by nadchif** [comment]
> so basically i have to remove the focus when we move the mouse away?

The idea is to prevent the picker from getting focus IF the mouse leaves, and the buttons had not been clicked. 
If the buttons have been clicked, the picker must receive focus.

**Comment by Kharanshu31** [comment]
I have done a change,pls look into it
