### ISSUE TITLE
Add an additional new line in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nadchif** [nadchif/html-duration-picker.js#9]
Good for first timers

Need help to insert an additional new line between "request. " and "Resources" in CONTRIBUTING.md

CURRENT ISSUE: There is just one "enter" (return/new line) after the word "pull request" on step 6. As a result, when you view the file on github, it appears something like this:
```
6. Create a pull request. Resources:

```
WHAT WE NEED: The word Resources should be on the next line, like this:
```
6. Create a pull request.
   Resources:

```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/html-duration-picker.js/blob/master/CONTRIBUTING.md)

**Comment by meisty** [comment]
@nadchif Can I pickup this issue please?

**Comment by meisty** [comment]
https://github.com/nadchif/html-duration-picker.js/pull/11

**Comment by nadchif** [comment]
Thank you @meisty for helping us out with this one.

**Comment by AregbesolaOJ** [comment]
thank you @nadchif i'd take this issue #9 and fix it

**Comment by AregbesolaOJ** [comment]
ooh looks like it's been fixed already eh? and closed
